INGENIC_VIDEOCAP_VERSION = 81b00fa4ae9c368f4ba025c911db29daf450928b
INGENIC_VIDEOCAP_SITE = https://github.com/openmiko/ingenic_videocap.git
INGENIC_VIDEOCAP_SITE_METHOD = git
INGENIC_VIDEOCAP_DEPENDENCIES =
INGENIC_VIDEOCAP_CONF_OPTS =

$(eval $(cmake-package))
