INGENIC_VIDEOCAP_VERSION = 698e0c803d2f551ee130e7e34ae249d22bcb2388
INGENIC_VIDEOCAP_SITE = https://github.com/openmiko/ingenic_videocap.git
INGENIC_VIDEOCAP_SITE_METHOD = git
INGENIC_VIDEOCAP_DEPENDENCIES =
INGENIC_VIDEOCAP_CONF_OPTS =

$(eval $(cmake-package))
