INGENIC_VIDEOCAP_VERSION = 759da3be2afe4ef93b025fc3723acbeb44ca9e25
INGENIC_VIDEOCAP_SITE = https://github.com/openmiko/ingenic_videocap.git
INGENIC_VIDEOCAP_SITE_METHOD = git
INGENIC_VIDEOCAP_DEPENDENCIES =
INGENIC_VIDEOCAP_CONF_OPTS =

$(eval $(cmake-package))
