#!/bin/sh
#
# Starts sshd.
#

start() {

	echo -n "Starting sshd: "
	/usr/bin/sshd
	[ $? == 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	echo -n "Stopping sshd: "
	start-stop-daemon -K -q -p /var/run/sshd.pid
	[ $? == 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
