#!/bin/bash
#
# Start logging
#

. /etc/openmiko.conf

start() {
	printf "Starting logging: "

	if [ "$ENABLE_LOGGING" == "0" ]; then
		mv /etc/logrotate.d/autonight.conf /etc/logrotate.d/autonight.conf~ || true
		mv /etc/logrotate.d/lighttpd.conf /etc/logrotate.d/lighttpd.conf~ || true
		mv /etc/logrotate.d/videocapture.conf /etc/logrotate.d/videocapture.conf~ || true
		mv /etc/logrotate.d/wpa_supplicant.conf /etc/logrotate.d/wpa_supplicant.conf~ || true
	else
		mv /etc/logrotate.d/autonight.conf~ /etc/logrotate.d/autonight.conf || true
		mv /etc/logrotate.d/lighttpd.conf~ /etc/logrotate.d/lighttpd.conf || true
		mv /etc/logrotate.d/videocapture.conf~ /etc/logrotate.d/videocapture.conf || true
		mv /etc/logrotate.d/wpa_supplicant.conf~ /etc/logrotate.d/wpa_supplicant.conf || true
	fi

	start-stop-daemon -b -S -q -m -p /var/run/syslogd.pid --exec /sbin/syslogd -- -n
	start-stop-daemon -b -S -q -m -p /var/run/klogd.pid --exec /sbin/klogd -- -n
	echo "OK"
}

stop() {
	printf "Stopping logging: "
	start-stop-daemon -K -q -p /var/run/syslogd.pid
	start-stop-daemon -K -q -p /var/run/klogd.pid
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
