#!/bin/bash
#
# Start crond
#

start() {
  LOG_LEVEL=4

  if [ "$ENABLE_LOGGING" == "0" ]; then
    LOG_LEVEL=8
  fi

  printf "Starting crond: "
  start-stop-daemon -b -S -q -m -p /var/run/crond.pid --exec /usr/sbin/crond -- -l ${LOG_LEVEL}
  echo "OK"
}

stop() {
  printf "Stopping crond: "
  start-stop-daemon -K -q -p /var/run/crond.pid
  echo "OK"
}

case "$1" in
  start)
  start
  ;;
  stop)
  stop
  ;;
  restart|reload)
  stop
  start
  ;;
  *)
  echo "Usage: $0 {start|stop|restart}"
  exit 1
esac

exit $?
