#!/bin/sh
#
#

case "$1" in
  start)
	. /usr/bin/libgpio.sh
	gpio_select_gpiochip 0

	gpio_export 25
	gpio_export 26

	;;
  stop)
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


