#!/bin/sh
#
#

case "$1" in
  start)
	. /usr/bin/libgpio.sh
	gpio_select_gpiochip 0

	gpio_export '25'
	gpio_export '26'
	gpio_export '49'

	# Turn on power to USB port (needed for older FCC IDs 2ANJHWYZEC02)
	gpio_export '47'
	gpio_direction_output '47'
	gpio_set_value '47' '1'

	;;
  stop)
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


