#!/bin/sh
#
# Mounts sdcard
#

case "$1" in
  start)
 	echo "Mounting  /sdcard"

	echo 43 > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio43/direction
	sleep 3

	if [ -e /dev/mmcblk0p1 ]; then
		mkdir -p /sdcard
		mount /dev/mmcblk0p1 /sdcard
		sleep 1
		echo "Mount /sdcard successful"

		# Write log files to the sdcard
		mkdir -p /sdcard/var/log
		cp -r /var/log/* /sdcard/var/log
		rm /var/log
		mkdir -p /var/log
		mount /sdcard/var/log /var/log
	fi;

	;;
  stop)
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


