#!/bin/bash
#
# Mounts flash partitions that are not rewritten on a firmware update
#

case "$1" in
  start)
 	echo "Mounting flash partitions"

	if [ -d /config ]
	then
		umount /config
	fi
	mount -t jffs2 /dev/mtdblock3 /config

	if [ $? -ne 0 ]
	then
		echo "Erasing /dev/mtd3 due to unclean mount"
		/usr/sbin/flash_eraseall /dev/mtd3
		mount -t jffs2 /dev/mtdblock3 /config/
		touch /config/.initialized
	fi


	# Should implement an optimization here to check for each file
	# so we don't wear out flash chip
	if [ -d /sdcard/config/ ]
	then
		echo "Copying files from sdcard to flash storage"
		cp -rv /sdcard/config/* /config
	fi

	echo "Copying files from flash storage to ram"

	# Overlay the config flash with the rootfs in memory
	cp -rv /config/overlay/* /

	;;
  stop)
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


