#!/bin/sh
#
# Start the wifi....
#

# Set default WIFI_MODULE
WIFI_MODULE=8189fs

. /etc/openmiko.conf

case "$1" in
  start)

	logger -s "Starting wifi using module $WIFI_MODULE" 

	modprobe $WIFI_MODULE

	CONFIGPATH="/etc"

	# If there is a file called wpa_supplicant.conf then copy it
	if [[ -e "/sdcard/wpa_supplicant.conf" ]]; then
		cp /sdcard/wpa_supplicant.conf "$CONFIGPATH/wpa_supplicant.conf"
	fi

	wpa_supplicant -Dnl80211 -i wlan0 -c "$CONFIGPATH/wpa_supplicant.conf" -B

	HOSTNAME=`cat /etc/hostname`

	udhcpc -i wlan0 -b -A 20 -x hostname:$HOSTNAME

	;;
  stop)
	printf "Stopping wifi..."
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


