#!/bin/bash
#
# Start the wifi....
#

# Set default WIFI_MODULE
WIFI_MODULE=8189fs

. /etc/openmiko.conf

case "$1" in
  start)
	logger -s "Starting wifi using module $WIFI_MODULE" 

	# Try to get the Wyze MAC address
	WIFI_OPTIONS=""
	if [[ "$USE_WYZE_MAC" -eq "1" ]] && [[ -f "/params/config/.product_config" ]]; then
		MAC=$(awk -F= '/NETRELATED_MAC/ {print substr($2, 1, 12)}' /params/config/.product_config | sed 's/\(..\)/\1:/g;s/:$//')
		logger -s "Using MAC $MAC"
		WIFI_OPTIONS="rtw_initmac=$MAC"
	fi

	modprobe $WIFI_MODULE $WIFI_OPTIONS

	CONFIGPATH="/etc"

	# If there is a file called wpa_supplicant.conf then copy it
	if [[ -e "/sdcard/wpa_supplicant.conf" ]]; then
		cp /sdcard/wpa_supplicant.conf "$CONFIGPATH/wpa_supplicant.conf"
	fi

	# Remove any \r line endings incase this was done on Windows
	#
	# :a create a label 'a'
	# N append the next line to the pattern space
	# $! if not the last line, ba branch (go to) label 'a'
	# s substitute, /\n/ regex for new line, / / by a space, /g global match (as many times as it can)
	# https://stackoverflow.com/questions/1251999/how-can-i-replace-a-newline-n-using-sed
	sed -i ':a;N;$!ba;s/\r//g' "$CONFIGPATH/wpa_supplicant.conf"


	if [ "$ENABLE_LOGGING" == "1" ]; then
		ADDITIONAL_FLAGS="-f /var/log/wpa_supplicant.log"
	fi

	wpa_supplicant -Dnl80211 -i wlan0 -c "$CONFIGPATH/wpa_supplicant.conf" -B -d $ADDITIONAL_FLAGS

	HOSTNAME=$(cat /etc/hostname)

	logger -s "Using hostname: $HOSTNAME"
	logger -s "Attempting DHCP"

	# -i Interface wlan0
	# -b Background if lease is not obtained
	# -A 20 Wait if lease is not obtained in 20 seconds
	# -S Log to syslog
	# -t 5 Send up to 5 discover packets (default 3)
	# -n exit if lease is not obtained

	udhcpc -i wlan0 -b -A 10 -S -t 6 -n -x hostname:$HOSTNAME
	ifconfig | logger -s

	;;
  stop)
	printf "Stopping wifi..."
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


