#!/bin/sh
#
# Start network time daemon
#

case "$1" in
  start)
 	echo -n "Starting ntpd: "
	ntpd
	[ $? == 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	echo -n "Stopping ntpd: "
	killall ntpd
	[ $? == 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

