#!/bin/bash
#
# Starts lighttpd.
#

. /etc/openmiko.conf

start() {
	printf "Starting lighttpd: "

	if [ "$ENABLE_LOGGING" == "1" ]; then
		cp /etc/lighttpd/conf.d/access_log.conf.enabled /etc/lighttpd/conf.d/access_log.conf
		cp /etc/lighttpd/conf.d/error_log.conf.enabled /etc/lighttpd/conf.d/error_log.conf
	else
		echo "" > /etc/lighttpd/conf.d/access_log.conf
		echo "" > /etc/lighttpd/conf.d/error_log.conf
	fi

	start-stop-daemon -S -q -p /var/run/lighttpd.pid --exec /usr/sbin/lighttpd -- -f /etc/lighttpd/lighttpd.conf
	echo "OK"
}
stop() {
	printf "Stopping lighttpd: "
	start-stop-daemon -K -q -p /var/run/lighttpd.pid
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
