#!/bin/sh
#
# Start video and camera
#

case "$1" in
  start)

	AUTH_PARAMS=""

	if [[ -f /etc/v4l2rtspserver.conf ]]; then
		echo "Reading parameters from /etc/v4l2rtspserver.conf"
		. /etc/v4l2rtspserver.conf

		AUTH_PARAMS="-R $HTTP_AUTH_REALM -U $USERNAME:$PASSWORD"
	fi

	echo "Adding necessary camera modules"

	modprobe sinfo
	modprobe tx-isp isp_clk=100000000

	if ! lsmod | grep -wq sensor_jxf23; then
		insmod /driver/sensor_jxf23.ko data_interface=2 pwdn_gpio=-1 reset_gpio=18 sensor_gpio_func=0
	fi

	# Turn on the infared cutoff filter (normal light operation)
	. /usr/bin/libgpio.sh

	gpio_select_gpiochip 0
	gpio_direction_output 25
	gpio_direction_output 26

	gpio_set_value 25 0
	gpio_set_value 26 1
	sleep 1
	gpio_set_value 26 0

	# For some reason if I load the v4l2rtspserver with live555 before
	# loading the ALSA loopback module userspace can't seem to see
	# the ALSA device. Not sure why but order matters here.

	modprobe snd-aloop index=0 pcm_substreams=2 enable=1

	# Disabling sound for now until we can look into the bugs more
	sleep 1
	#ffmpeg -fflags +genpts -re -nostats -nostdin -f oss -i /dev/dsp -codec:a copy -f alsa hw:0,0 > /dev/null &

	modprobe v4l2loopback devices=2

	if ! ps | grep -wq [v]ideocapture; then
		echo "Starting video frame capture process"
		/usr/bin/videocapture /etc/videocapture_settings.json > /dev/null 2>&1 &

        # Wait for the videocapture program to initialize the v4l2 device
        MAX_WAIT=5
        i=0
        while [[ -e $(fuser /dev/video3) ]]
        do
                echo "Waiting for initialization of v4l2 device"
                sleep 1
                i=`expr $i + 1`
                if [[ $i -gt $MAX_WAIT ]]
                then
                        echo "Unable to initialize v4l2 device"
                        break
                fi
        done
	fi

	# This command includes the ALSA hardware but we are disabling for now
	#/usr/bin/v4l2rtspserver /dev/video3,hw:0,1 > /var/log/v4l2rtspserver.log &

	if ! ps | grep -wq [v]4l2rtspserver; then
		echo "Starting v4l2rtspserver"
		#/usr/bin/v4l2rtspserver $AUTH_PARAMS -l 1 -A 48000 -C 1 -a S16_LE /dev/video3,hw:0,1 /dev/video4 > /dev/null &
		/usr/bin/v4l2rtspserver $AUTH_PARAMS /dev/video3 /dev/video4 > /dev/null &
	fi

	# Waiting for v4l2rtpserver to start
	sleep 5

	FFMPEG_CMD="ffmpeg -nostats -nostdin"
	RTSP_TRANSPORT="-rtsp_transport tcp -i rtsp://$USERNAME:$CLEARTEXT_PASSWORD@127.0.0.1:8554/video3/unicast"

	SEGMENT_ARGS="-f segment -segment_time 600 -segment_format mp4 -segment_wrap 60"

	if [ "$ENABLE_RECORDING" = "1" ]; then
		echo "Starting recording using ffmpeg"
		mkdir -p /sdcard/recordings
		FFMPEG_CMD="$FFMPEG_CMD $RTSP_TRANSPORT -c:v copy $SEGMENT_ARGS -reset_timestamps 1 -strftime 0 -movflags frag_keyframe -c copy -map 0 /sdcard/recordings/segment-%04d.mp4"
		echo $FFMPEG_CMD
		$FFMPEG_CMD > /dev/null 2>&1 &
	fi


	;;
  stop)
	killall videocapture
	killall v4l2rtspserver
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
