#!/bin/sh
#
# Start mjpg-streamer
#

if [[ -f /etc/openmiko.conf ]]; then
	. /etc/openmiko.conf
fi

case "$1" in
  start)

	if [ "$ENABLE_MJPEG_OVER_HTTP" != "1" ]; then
		exit 0
	fi

 	echo -n "Starting mjpg_streamer ($MJPEG_FPS fps): "
	mjpg_streamer -i "input_v4l2loopback.so -d /dev/video4 --fps $MJPEG_FPS" -o "output_http.so" > /dev/null 2>&1 &
	[ $? == 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	echo -n "Stopping mjpg_streamer: "
	killall mjpg_streamer
	[ $? == 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
