#!/bin/sh

#output=/dev/null
output=/tmp/mdev.log

echo "mdev udisk message: $DEVPATH" >> $output
echo "mdev udisk message devpath: ${DEVPATH:33:8} " >> $output

echo "1 4 1 4" > /proc/sys/kernel/printk

if [ "$ACTION" == "add" ]; then
{
    mkdir -p /media/udisk
    mount /dev/$MDEV /media/udisk
    echo "add a udisk: ${PWD}/${DEVNAME}" >> $output
}
elif [ "$ACTION" == "remove" ]; then
{
    echo "remove a udisk: ${PWD}/${DEVNAME}" >> $output
    umount  /media/udisk
    sleep 1
    rm -rf /media/udisk
}
fi
